chatgpt/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('chatting/', views.home, name='chatbot'),
]

finalemobilisprojrct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from socialmedia.views import custom_media_serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socialmedia.urls')),
    path('chat/', include('chatgpt.urls')),
    path('videochat/', include('videocall.urls')),
    path('entertainment/', include('entertainment.urls')),
    path('library/', include('library.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += [path('media/<path:path>/', custom_media_serve)]

# Serving media files during development
# if settings.DEBUG:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from library import views

urlpatterns = [
    path('', views.home, name='libraryhome'),
    path('uploadfile/', views.bookupload, name='newBook'),
    path('addcategory/', views.addcategory, name='newcategory'),
    path('sales/', views.checkmytotalsales, name='info'),
    path('mybooks/', views.mybooks, name='mybook'),
    path('forsale/<str:title>', views.checkbooksales, name='bookinfosale'),
    path('cpurchase/<str:customer>', views.checkcustomerpurches, name='customerpurchase'),
    path('editfile/<int:pk>', views.edit_book, name='editbook'),
    path('description/<str:description>', views.book_description, name='describebook'),
    path('available/<str:pk>', views.mainbookinformation, name='MainbookDescription'),
    path('buy/<str:pk>', views.buybook, name='buybook'),
    path('searchbyct/<str:ctname>/', views.searchwithcategory, name='searchbycategoty'),
    path('delete/<int:pk>', views.deletebook, name='deletebook'),
    path('mpesa-callback/', views.mpesa_callback, name='mpesa_callback'),
 ]

library/models.py
from django.db import models

from socialmedia.models import User


# Create your models here.
class Framework(models.Model):
    framework_name = models.CharField(max_length=20)
    framework_description = models.TextField(max_length=100)
    updated_at = models.DateTimeField(auto_now=True)
    frameworks_image = models.ImageField(null=False, upload_to='framework/')

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.framework_name


class Category(models.Model):
    category_name = models.CharField(max_length=20)
    category_image = models.ImageField(null=True, upload_to='languages/', default="book_cover/bg2.png")
    category_description = models.CharField(max_length=50)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.category_name


class MainBooks(models.Model):
    option = (('sale', 'sale'), ('free', 'free'))
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    topic = models.CharField(max_length=250)
    published_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=False, upload_to='book_cover/')
    book = models.FileField(null=False, upload_to='books/')
    type = models.CharField(max_length=10, choices=option, default='free')
    amount = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.title


class BookBought(models.Model):
    book = models.ForeignKey(MainBooks, null=False, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True, null=True)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return self.book.title

library/forms.py
from django import forms
from .models import MainBooks, Category


class MainBooksForm(forms.ModelForm):
    class Meta:
        model = MainBooks
        fields = '__all__'
        exclude = ['auther']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

library/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .credentials import MpesaAccessToken, LipanaMpesaPpassword
from .forms import MainBooksForm, CategoryForm
from .models import MainBooks, Category, Framework, BookBought

api_key = 'AIzaSyCTm9EWtvOvEtiRIlnIH5sH0XETPz8Mf3A'
user = ''


@login_required(login_url='login')
def home(request):
    search = 'python'
    sr = ''
    check = request.GET.get('search', '')
    if request.method == 'GET' and check != '':
        search = request.GET.get('search', 'java')
        sr = search
    books_data = fetch_books_data(request, search)
    main_books_data = main_books(request, sr)
    framework = frameworks(request)
    category = categories(request)
    book1 = []
    book2 = []
    book3 = []
    i = 0
    k = 0
    for book in main_books_data:
        if k < 5 and book.type == "free":
            book1.append(book)
            k += 1
        elif k < 5 and book.type == "free":
            book2.append(book)
            k += 1
        else:
            pass
        book3.append(book)
        i += 1
    context = {
        "books": books_data,
        "books2": book2,
        "main_books": book1,
        "category": category,
        "framework": framework,
        "book3": book3
    }

    return render(request, 'library/index.html', context)


def searchhome(request, search):
    check = request.GET.get('search', '')
    if request.method == 'GET' and check != '':
        search = request.GET.get('search', 'java')
    books_data = fetch_books_data(request, search)
    main_books_data = main_books(request, search)
    framework = frameworks(request)
    category = categories(request)
    book1 = []
    book2 = []
    book3 = []
    i = 0
    k = 0
    for book in main_books_data:
        if k < 5 and book.type == "free":
            book1.append(book)
            k += 1
        elif k < 5 and book.type == "free":
            book2.append(book)
            k += 1
        else:
            pass
        book3.append(book)
        i += 1

    context = {
        "books": books_data,
        "books2": book2,
        "main_books": book1,
        "category": category,
        "framework": framework,
        "book3": book3
    }

    return render(request, 'library/index.html', context)


@login_required(login_url='login')
def fetch_books_data(request, query):
    base_url = 'https://www.googleapis.com/books/v1/volumes'
    params = {
        'q': query,
        'key': api_key,
    }

    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()
        books = []
        for book in response.json().get('items', []):
            volume_info = book.get('volumeInfo', {})

            books.append({
                "bookinfo": book.get('id', ''),
                "title": volume_info.get('title', ''),
                "image": volume_info.get('imageLinks', {}).get('thumbnail', ''),
            })

        return books
    except requests.exceptions.RequestException as e:
        print(e)


def main_books(request, search):
    if search == 'none' or search == '' or search == None:
        books = MainBooks.objects.all().order_by('-updated_at')
    else:
        books = MainBooks.objects.filter(
            Q(title__icontains=search) |
            Q(auther__name__icontains=search) |
            Q(auther__username__icontains=search) |
            Q(auther__email__icontains=search) |
            Q(type__icontains=search) |
            Q(category__category_name__icontains=search) |
            Q(description__icontains=search)
        ).order_by('-updated_at')
    return books


def categories(request):
    category = Category.objects.all().order_by('-updated_at')
    return category


def frameworks(request):
    framework = Framework.objects.all().order_by('-updated_at')
    return framework


import requests


@login_required(login_url='login')
def book_description(request, description):
    base_url = 'https://www.googleapis.com/books/v1/volumes'
    params = {'q': description}

    response = requests.get(base_url, params=params)
    datainfo = []
    if response.status_code == 200:
        data = response.json()
        if 'items' in data:
            first_item = data['items'][0]['volumeInfo']
            datainfo.append({
                "title": first_item.get('title', 'N/A'),
                "description": first_item.get('description', 'N/A'),
                "authors": first_item.get('authors', ['N/A']),
                "date_published": first_item.get('publishedDate', 'N/A'),
                "pdf_link": first_item.get('pdfLink', 'Not Available'),
                "is_for_sale": first_item.get('saleInfo', {}).get('saleability', 'Not Available'),
                "image_link": first_item.get('imageLinks', {}).get('thumbnail', 'Not Available'),
                "page_count": first_item.get('pageCount', 'N/A')
            })

    return render(request, 'library/book_description.html', {"bookinfo": datainfo})


@csrf_exempt
@login_required(login_url='login')
def bookupload(request):
    if request.method == 'POST':
        form = MainBooksForm(request.POST, request.FILES)
        if form.is_valid():
            if request.user.is_authenticated:
                book, book_created = MainBooks.objects.get_or_create(
                    title=form.cleaned_data['title'],
                    description=form.cleaned_data['description'],
                    topic=form.cleaned_data['topic'],
                    auther=request.user,
                    image=form.cleaned_data['image'],
                    book=form.cleaned_data['book'],
                    type=form.cleaned_data['type'],
                    amount=form.cleaned_data['amount'],
                    category=form.cleaned_data['category'],
                )

                if book_created:
                    # return JsonResponse({'success': True, 'redirect_url': f'/library/mainbookinformation/{book.pk}/'})
                    return mainbookinformation(request, book.pk)
                else:
                    return JsonResponse({'success': False, 'error': 'Book already exists'})
            else:
                return JsonResponse({'success': False, 'error': 'User not authenticated'})
        else:
            return JsonResponse({'success': False, 'error': 'Form is not valid'})
    else:
        form = MainBooksForm()
    context = {'form': form}
    return render(request, 'library/fileUpload.html', context)


def mainbookinformation(request, pk):
    book = MainBooks.objects.get(pk=pk)
    try:
        customer = BookBought.objects.get(customer=request.user, book=book)
    except BookBought.DoesNotExist:
        customer = ''
    context = {"book": book, "customer": customer}
    return render(request, 'library/mainBookDescription.html', context)


@csrf_exempt
def buybook(request, pk):
    book = get_object_or_404(MainBooks, pk=pk)

    if request.method == 'POST':
        phone = request.POST['phone']
        amount = int(book.amount)
        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        headers = {"Authorization": "Bearer %s" % access_token}
        mpesa_request = {
            "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
            "Password": LipanaMpesaPpassword.decode_password,
            "Timestamp": LipanaMpesaPpassword.lipa_time,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": 254757316903,
            "PartyB": LipanaMpesaPpassword.Business_short_code,
            "PhoneNumber": phone,
            "CallBackURL": "https://a8f3-102-215-13-135.ngrok-free.app/mpesa-callback/",
            "AccountReference": f"mesh library username: {request.user.username}: title {book.title}",
            "TransactionDesc": "Web Development Charges"
        }
        requests.post(api_url, json=mpesa_request, headers=headers)
        BookBought.objects.get_or_create(
            book=book,
            customer=request.user,
            amount=amount
        )
        try:
            cm = BookBought.objects.get(customer=request.user, book=book)
        except BookBought.DoesNotExist:
            cm = ''
        context = {"book": book, "customer": cm}
        return render(request, 'library/mainBookDescription.html', context)
    try:
        customer = BookBought.objects.get(customer=request.user, book=book)
    except BookBought.DoesNotExist:
        customer = None
    context = {"book": book, "customer": customer}
    return render(request, 'library/buybook.html', context)


from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


@csrf_exempt
def mpesa_callback(request):
    if request.method == 'POST':
        # Parse the JSON data from the callback
        callback_data = json.loads(request.body)

        # Extract relevant information from the callback_data
        transaction_status = callback_data.get('Body', {}).get('stkCallback', {}).get('ResultCode')

        # Check if the transaction was canceled (adjust the status code based on Safaricom's documentation)
        if transaction_status == 'Cancelled':
            return HttpResponse("cancelled")
        # Update your application state to reflect the cancellation (mark the transaction as canceled in your database, for example)

        # Notify the user about the cancellation (you might want to implement this based on your application's requirements)

        # Perform any necessary cleanup steps

        # Return a response to Safaricom
        return HttpResponse(json.dumps({"ResultCode": "0", "ResultDesc": "Success"}), content_type='application/json')

library/templates/library/edit_book.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'library/css/bookUpload.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
{% block content %}
    <section>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container d-flex justify-content-between">
                <div>
                    {% for formfield in form %}
                        {% if formfield.name != 'image' and formfield.name != 'book' %}
                            <div>
                                <label for="{{ formfield.name }}" class="form-label">{{ formfield.label }}</label>
                                <p class="form-control" style="font-size: 20px">{{ formfield }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
                    {% for formfield in form %}
                        {% if formfield.name == 'image' %}
                            <div class="d-flex justify-content-center align-items-center flex-column mt-5"
                                 style="height: 75%">
                                <div id="imageDropArea" class="drop-area"
                                     style="height:250px;background-image:linear-gradient(#0d5e3e,rgba(24,128,86,0.5),#0d5e3e),url('{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static "images/img.png" %}{% endif %}');background-repeat: no-repeat; background-size: cover;background-position: center">
                                    <p class="text-white">Drag and drop cover here or click to select</p>
                                </div>
                                <p class="d-none">{{ formfield }}</p>
{#                                <label for="id_image" class="form-label btn btn-success mt-3 w-100 text-center" style="font-size: 20px; background-color: dimgrey;">Upload the cover</label>#}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
                    {% for formfield in form %}
                        {% if formfield.name == 'book' %}
                            <div class="d-flex justify-content-center align-items-center flex-column mt-5"
                                 style="height: 75%">
                                <div id="bookDropArea" class="drop-area"
                                     style="height:250px;background-image:linear-gradient(#0d5e3e,rgba(24,128,86,0.5),#0d5e3e),url('{% if form.instance.book %}{{ form.instance.book.url }}{% else %}{% static "images/img.png" %}{% endif %}');background-repeat: no-repeat; background-size: cover;background-position: center">
                                    <p class="text-white">Drag and drop files here or click to select</p>
                                </div>
                                <p class="d-none">{{ formfield }}</p>
{#                                <label for="id_book" class="form-label btn btn-success mt-3 w-100 text-center" style="font-size: 20px; background-color: dimgrey;">Upload book here</label>#}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <input type="submit" value="{% if form.instance %}UPDATE{% else %}SUBMIT BOOK{% endif %}" class="btn btn-success text-center w-75 d-flex justify-content-center m-auto" style="font-size: 20px">
        </form>
    </section>
    {% include 'library/footer.html' %}
    <script src="{% static 'library/js/bookUpload.js' %}"></script>
{% endblock %}

library/templates/library/fileUpload.html
{% extends 'main.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'library/css/bookUpload.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
            @media (max-width: 767px) {
                .container{
                    display: flex;
                    flex-direction: column;
                }
            }
    </style>
{% endblock %}

{% block content %}
    <section>
        <form id="uploadForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container d-flex justify-content-between">
                <div>
                    {% for formfield in form %}
                        {% if formfield.name != 'image' and formfield.name != 'book' %}
                            <div>
                                <label for="{{ formfield.name }}" class="form-label">{{ formfield.label }}</label>
                                <p class="form-control" style="font-size: 20px">{{ formfield }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
                    {% for formfield in form %}
                        {% if formfield.name == 'image' %}
                            <div class="d-flex justify-content-center align-items-center flex-column mt-5">
                                <div id="imageDropArea" class="drop-area"
                                     style="height:250px; background-image:linear-gradient(#0d5e3e,rgba(24,128,86,0.5),#0d5e3e), url('{% static "images/img.png" %}'); background-repeat: no-repeat; background-size: cover; background-position: center" >
                                    <p class="text-white">Drag and drop cover here or click to select</p>
                                </div>
                                <input type="file" name="{{ formfield.name }}" accept="image/*" class="d-none">
{#                                <label for="id_image" class="form-label btn btn-success mt-3 w-100 text-center" style="font-size: 20px; background-color: dimgrey;">Upload the cover</label>#}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
                    {% for formfield in form %}
                        {% if formfield.name == 'book' %}
                            <div class="d-flex justify-content-center align-items-center flex-column mt-5">
                                <div id="bookDropArea" class="drop-area"
                                     style="height:250px; background-image:linear-gradient(#0d5e3e,rgba(24,128,86,0.5),#0d5e3e), url('{% static "images/img.png" %}'); background-repeat: no-repeat; background-size: cover; background-position: center">
                                    <p class="text-white">Drag and drop files here or click to select</p>
                                </div>
                                <input type="file" name="{{ formfield.name }}" accept=".pdf" class="d-none">
{#                                <label for="id_book" class="form-label btn btn-success mt-3 w-100 text-center" style="font-size: 20px; background-color: dimgrey;">Upload book here</label>#}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <input type="submit" value="SUBMIT BOOK" class="btn btn-success text-center w-75 d-flex justify-content-center m-auto" style="font-size: 20px">
        </form>
        <progress id="fileUploadProgress" value="0" max="100"></progress>
    </section>

    {% include 'library/footer.html' %}
    <script src="{% static 'library/js/bookUpload.js' %}"></script>
{% endblock %}

library/templates/library/mybooks.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'library/css/mybooks.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock head %}
{% block content %}
    <div class="main">
        <div class="main1"
             style="background: linear-gradient(rgba(57,182,156,0.5),rgba(20,119,94,0.5),rgba(57,182,156,0.5)),url('{% static "images/img_2.png" %}')">
            <div class="d-flex justify-content-end " style="background-color: #0f5132">
                <a href="{% url 'newBook' %}" class="btn btn-secondary"><h2 class="section-title" style="color: white;">
                    ADD BOOK</h2></a>
                <a href="{% url 'newcategory' %}" class="btn btn-secondary"><h2 class="section-title"
                                                                                style="color: white;">ADD Category</h2>
                </a>
                <a href="{% url 'info' %}" class="btn btn-secondary"><h2 class="section-title" style="color: white;">My
                    sales</h2></a>
            </div>
            <div id="carouselExampleIndicators" class="carousel slide " style="height:25%">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                            class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner" style="margin-top: 20%">
                    <div class="carousel-item active">
                        <h1>Welcome to Mesh Library</h1>
                        <p>Your go-to destination for a vast collection of books, resources, and knowledge.</p>
                    </div>
                    <div class="carousel-item">
                        <h2>Featured Books</h2>
                        <p>Explore our carefully curated selection of books, including bestsellers, classics, and hidden
                            gems. We believe in the power of reading to inspire, educate, and entertain.</p>

                    </div>
                    <div class="carousel-item">
                        <h2>Categories</h2>
                        <p>Dive into specific areas of interest with our categorized collection. From fiction to
                            non-fiction, science to history, our library covers it all.</p>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="main2">
            <h1>My books</h1>
            <div class="main3">
                {% for book in main_books %}
                    <div class="element mx-auto bg-white rounded" style="height: 300px; min-width: 23%;margin-top: 10px">
                        <div class="mx-auto" style="width: 90%">
                            <img src="{{ book.image.url }}" alt="{{ book.title }}" style="width:100%; height: 200px"
                                 class="mt-3">
                            <a href="{% url 'MainbookDescription' book.id %}" class="btn w-100 mt-3 view btn-success"
                               style="font-size: 20px;color: black">view book</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div style="margin-top: 40px">{% include 'library/footer.html' %}</div>
        </div>
        {#        <div class="books-container">#}
        {#            {% for book in main_books %}#}
        {#                <div class="book">#}
        {#                    <img src="{{ book.image.url }}" alt="{{ book.title }}" style="width:150px">#}
        {#                    <h3>{{ book.title }}</h3>#}
        {#                    <p>{{ book.description }}</p>#}
        {#                    <p>Author: {{ book.auther.username }}</p>#}
        {#                    <p>Type: {{ book.get_type_display }}</p>#}
        {#                    {% if book.type == 'sale' %}#}
        {#                        <p>Amount: {{ book.amount }}</p>#}
        {#                    {% endif %}#}
        {#            <a href="{% url '' description=book.title %}">View Details</a>#}
        {#                </div>#}
        {#            {% endfor %}#}
        {#        </div>#}
    </div>


{% endblock content %}

library/templates/library/uploadCategory.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'library/css/category.css' %}">
{% endblock %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for form in form %}
            {% if form.name != 'category_image' %}
                <div>
                    <label for="{{ form.name }}" class="form-label">{{ form.label }}</label>
                    <p class="form-control">{{ form }}</p>
                </div>
            {% endif %}
        {% endfor %}
        {% for form in form %}
            {% if form.name == 'category_image' %}
                <div>
                    <label for="{{ form.name }}" class="form-label">{{ form.label }}</label>
                    <p class="d-none">{{ form }}</p>
                    <div class="d-flex justify-content-center align-items-center flex-column mt-5"
                         style="height: 75%">
                        <label id="bookDropArea" class="drop-area imageDropArea" for="id_category_image"
                               style="background-image:linear-gradient(#0d5e3e,rgba(24,128,86,0.5),#0d5e3e),url('{% static "images/img.png" %}');">
                            <p class="text-white">click to select</p>
                        </label>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="w-100 justify-content-center align-items-center d-flex"><input type="submit"
                                                                                   style="text-align: center; font-weight: bolder; font-size: 20px; margin-top: 20px;"
                                                                                   class=" btn btn-primary w-25"
                                                                                   value="submit"></div>
    </form>
    <script>
        document.querySelector("input[name='category_image']").addEventListener('change', (e) => {
            const fileInput = e.target;
            const dropArea = document.querySelector('.drop-area');
            if (fileInput.files.length > 0) {
                const file = fileInput.files[0];
                const imageUrl = URL.createObjectURL(file);

                dropArea.style.backgroundImage = `url(${imageUrl})`;
            }
        });
    </script>
{% endblock content %}